### ISSUE TITLE
Testes no Frontend

### ISSUE THREAD

**Issue by joaovitorml** [fga-eps-mds/2020.1-GaiaDex-FrontEnd#110]
Essa issue requer que no mínimo as seguintes telas/rotas sejam testadas, por meio de algum framework de testes (sugestões: enzyme ou Jest) a ser estabelecido pelos assignees dessa tarefa:
- [ ] Scanner
- [ ] Cadastro
- [ ] Login

**Comment by wdvictor** [comment]
Opa @joaovitorml, muito bom seu projeto, mas acredito q nao to podendo trabalhar com ele agora, final de semestre kkk. Mas vlw pelo assigned.

**Comment by joaovitorml** [comment]
Opa, me desculpa, um membro da nossa equipe também se chama Victor Hugo e
acabei te marcando no lugar dele por engano.

Em dom., 22 de nov. de 2020 às 14:12, Victor Hugo <notifications@github.com>
escreveu:
