### ISSUE TITLE
US07 - Fazer login no aplicativo (Frontend)

### ISSUE THREAD

**Issue by rafaelmakaha** [fga-eps-mds/2020.1-GaiaDex-FrontEnd#5]
**Descrição:**
---

Eu como usuário quero fazer login no aplicativo para acessar as demais funcionalidades do mesmo.

**Critérios de Aceitação:**
---

- [x] O sistema deve válidar os dados utilizados pelo usuário no login.
- [x] Em caso de falha de login por dados invalidos, o sistema deve informar que há dados invalidos (sem explicitar quais são).
- [x] Em caso de login valido, o sistema deve redirecionar o usuário à tela principal.
- [x] O sistema deve manter a sessão do usuário válida, até que ele decida deslogar.

**Critérios Extras:**
---

- [ ] O sistema deverá mostrar uma mensagem de boas-vindas

**Comment by joaovitorml** [comment]
Fechada devido a aceitação do PR #111
