### ISSUE TITLE
US08 - Fazer logout no aplicativo (FrontEnd)

### ISSUE THREAD

**Issue by rafaelmakaha** [fga-eps-mds/2020.1-GaiaDex-FrontEnd#6]
# Descrição
Eu como usuário quero fazer logout do aplicativo para sair da minha conta

# Critérios de Aceitação

- [x] O sistema deve invalidar a sessão do usuário
- [x] O sistema deve redirecionar o usuário à tela de login

**Critérios Extras:**
---

- [ ] O sistema deverá mostrar uma mensagem de despedida

**Comment by joaovitorml** [comment]
Fechada devido a aceitação do PR #111
