### ISSUE TITLE
US12 - Deletar minha conta (FrontEnd)

### ISSUE THREAD

**Issue by rafaelmakaha** [fga-eps-mds/2020.1-GaiaDex-FrontEnd#7]
**Descrição:**
---

Eu como usuário quero deletar minha conta para impedir o acesso a mesma permanentemente.

**Critérios de Aceitação:**
---

- [x] O sistema deve perguntar ao usuário se ele _realmente_ gostaria de deletar a conta ou não
- [x] O sistema deve invalidar a sessão do usuário
- [x] O sistema deve remover todos os dados pessoais do usuario do banco de dados

**Critérios Extras:**
---

- [ ] O sistema deve manter os tópicos e comentários nos fóruns (com a tag "usuario removido")
- [ ] O sistema deve remover os posts, comentários em posts (tanto em comunidades como no próprio feed)

**Comment by joaovitorml** [comment]
Fechada devido a aceitação do PR #111
