### ISSUE TITLE
US10 - Visualizar Configurações Da Conta

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-GaiaDex-FrontEnd#80]
**Descrição:**
---

Eu como usuário quero visualizar configurações da conta para personalizar de acordo com minhas preferencias.

**Critérios de Aceitação:**
---

- [x] O usuário poderá visualizar as Politicas de Privacidade do aplicativo
- [x] O usuário poderá visualizar os Termos de Uso
- [x] O usuário poderá visualizar botão de Ajuda
- [x] O usuário poderá visualizar o botão de Privacidade

**Critérios Extras:**
---

- [ ] O usuário poderá visualizar um botão de Definir Idioma

**Comment by joaovitorml** [comment]
Fechada pelo PR #118
