### ISSUE TITLE
US11 - Alterar os dados cadastrados na minha conta (FrontEnd)

### ISSUE THREAD

**Issue by rafaelmakaha** [fga-eps-mds/2020.1-GaiaDex-FrontEnd#9]
# Descrição

Eu como usuário quero alterar os dados da minha conta para mantê-los atualizados.

# Critérios de Aceitação

- [x] O usuário poderá alterar seu username
- [x] O usuário poderá alterar seu email
- [x] O usuário poderá alterar sua foto de perfil
- [x] O usuário poderá alterar sua senha
- [x] O sistema deve validar as modificações fornecidas pelo usuário

**Critérios Extras:**
---

- [ ] O usuário poderá definir um vídeo/gif curto como "foto" de perfil

**Comment by joaovitorml** [comment]
Fechado pela issue #111
