### ISSUE TITLE
US20 - Editar Comentário Que Fiz Em Um Tópico

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-GaiaDex-FrontEnd#90]
**Descrição:**
---

Eu como usuário quero editar comentário que fiz em um tópico para modificar um erro que eu tenha cometido.

**Critérios de Aceitação:**
---

- [x] O sistema deve validar o conteúdo do comentario, de forma a garantir que este não está vazio

**Critérios Extras:**
---

- [ ] O sistema deve explicitar que aquele comentário foi editado (com tag '[editado]' por exemplo)

**Comment by joaovitorml** [comment]
Resolvida pelo PR #103
