### ISSUE TITLE
US26 - Visualizar Minha Coleção De Favoritos

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-GaiaDex-FrontEnd#96]
**Descrição:**
---

Eu como usuário quero visualizar minha coleção de favoritos para facilitar o processo de navegação pelas páginas que mais visito.

**Critérios de Aceitação:**
---

- [x] O usuário poderá abrir os cards de planta diretamente da aba de favoritos
- [x] Cada widget das plantas adicionadas à coleção de favoritos deverá mostrar seu Nome Comum
- [x] Cada widget das plantas adicionadas à coleção de favoritos deverá mostrar seu nome científico
- [x] Cada widget das plantas adicionadas à coleção de favoritos deverá mostrar seu status de extinção
- [x] Cada widget das plantas adicionadas à coleção de favoritos deverá mostrar um botão que redireciona, também, ao card de planta

**Critérios Extras:**
---

- [ ] Cada widget das plantas adicionadas à coleção de favoritos deverá mostrar um botão de compartilhar (que compartilharia o link do card de planta)

**Comment by joaovitorml** [comment]
Issue fechada pelo PR #94
